spring.datasource.url=jdbc:mysql://localhost:3306/inmoprtest?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=tfm
spring.datasource.password=tfm

spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=never
